### ISSUE TITLE
Bugfixes from previous versions

### ISSUE THREAD

**Issue by robredpath** [open-contracting/ocds-show#11]

**Comment by robredpath** [comment]
https://opendataservices.titanpad.com/646

**Comment by edugomez** [comment]
> https://opendataservices.titanpad.com/646

Now at Sandstorm's  Etherpad https://opendataservices.sandcats.io/grain/ebKr5kECXRgzM6RspNR5qz

**Comment by robredpath** [comment]
@duncandewhurst and @kindly are talking shortly to discuss if any of the outstanding issues require attention

**Comment by kindly** [comment]
This is complete in ppp branch.
