### ISSUE TITLE
Get CoVE ready to accept extended + flattened+extended data

### ISSUE THREAD

**Issue by robredpath** [open-contracting/ocds-show#12]
Things that need doing.

- [x] Metatab pull request needs merging in flattentool
- [x] Cove needs to use flattentool to fetch versions and extensions before parsing the file normally.
- [x] Cove needs work to support versions and extensions in flattened data (Currently this only works with json)

**Comment by robredpath** [comment]
Added to this board for tracking alongside other related work rather than because it's ocds-show. All part of the 1.1/extensions work so should be time-tracked as upgrade work

**Comment by robredpath** [comment]
'get ready' includes updating documentation so that users know about the Metatab functionality

**Comment by edugomez** [comment]
In progress in related https://github.com/OpenDataServices/cove/issues/641

**Comment by robredpath** [comment]
Outstanding work at end of sprint:
- "the vertical thing"
- PR merge
- deploy

@duncandewhurst when does this need to be deployed by, for 1.1 or PPP purposes?

**Comment by duncandewhurst** [comment]
> when does this need to be deployed by, for 1.1 or PPP purposes?

For PPPs, ideally by 15th May but definitely by the 29th.

For 1.1, I'm not sure - @timgdavies?

**Comment by robredpath** [comment]
@timgdavies - do we know when CoVE for 1.1 needs to be live?

**Comment by timgdavies** [comment]
May 11th.

**Comment by jpmckinney** [comment]
@robredpath What is still outstanding on this issue?

**Comment by robredpath** [comment]
Pretty sure this is done. @Bjwebb ?
