### ISSUE TITLE
Create example data

### ISSUE THREAD

**Issue by robredpath** [open-contracting/ocds-show#13]
We need example data to make testing easier - in collaboration with @duncandewhurst

**Comment by duncandewhurst** [comment]
@kindly I've pulled together the examples from the extension readme files into a single file [here](https://drive.google.com/a/opendataservices.coop/file/d/0B79uNIOfT24ec0hVUTh0WHlxX1U/view?usp=sharing)

It's not very complete though so I would recommend also using the examples linked in the titanpad.

**Comment by jpmckinney** [comment]
Closing in favor of #17
