### ISSUE TITLE
Add basic tests and enable Travis

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-show#17]
https://github.com/open-contracting/standard-development-handbook/issues/41

**Comment by jpmckinney** [comment]
Related #13

**Comment by kindly** [comment]
@jpmckinney 
Have converted existing tests to use travis here https://github.com/open-contracting/ocds-show/pull/24

Not sure if it will work though as need travis enabled to test and do not have access to do that.

**Comment by jpmckinney** [comment]
I enabled Travis and will close the PR shortly.
