### ISSUE TITLE
Option to get the json from a query param url

### ISSUE THREAD

**Issue by yolile** [open-contracting/ocds-show#32]
It would be nice to have an option to include a query param of the type ?url=release-url to be able to embed the complete url and use it within an iframe directly without needing to deploy the application for its own use

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update & merge in work to add url query param to ocds-show](https://trello.com/c/YGWhSDNi/8-update-merge-in-work-to-add-url-query-param-to-ocds-show)

**Comment by jpmckinney** [comment]
Use the `load` parameter: https://open-contracting.github.io/ocds-show/?load=https://www.comprasestatales.gub.uy/ocds/release/llamado-631824
