### ISSUE TITLE
What is __extra?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-show#37]
@kindly I was recently reconciling the different versions of OCDS Show, OCDS Show for PPPs, and the specific instance of OCDS Show for PPPs in the PPP profile. I can't figure out what __extra is about. This is not a field that occurs in the OCDS schema.

The PR to add it was https://github.com/open-contracting/ocds-show/pull/30. [This file](https://github.com/open-contracting/ocds-show/blob/6be0c006e2feced6862e718eeb4d073393bc3c35/example/full_with_extra_fields.json) was added with `__extra` fields, but I don't know why.

**Comment by kindly** [comment]
@jpmckinney this was a mechanism for the ocds-show to display additional fields that were not in the schema including extensions.  However, it is only used in the data review tool here:

https://github.com/OpenDataServices/cove/blob/6319ebf4fcc8d575d392f328a03852035b3a8447/cove_ocds/lib/ocds_show_extra.py

It compares the data to fields in the schema and adds an __extra dict to each object to collate all the additional fields.

Ideally ocds show would have "schema awareness" and work out what fields were in the schema itself.  However, this was the quickest solution we could find to at least let the "data review tool" display additional fields.

**Comment by jpmckinney** [comment]
Thanks. This wasn't consistently implemented in the PPP templates, and wasn't updated in ocds-show-ppp, leading to inconsistencies that were hard to reconcile. I've updated both readmes with explicit lists of differences between ppp templates and between repos to make this easier in future.

For any future work, we should switch to extending base templates (only done in `organization_ppp.html`), instead of copying then editing them. #38
