### ISSUE TITLE
Legal Name links back to OCDS Show

### ISSUE THREAD

**Issue by ekoner** [open-contracting/ocds-show#4]
I'm viewing a record from ProZorro. In the Identifiers block of the Buyer section, the Legal Name is shown as a link. The link is to OCDS Show i.e. [Відділ освіти Перемишлянської райдержадміністрації](https://open-contracting.github.io/ocds-show/) - is this the intended behaviour?

**Comment by jpmckinney** [comment]
I assume this is because the HTML template expects a value to put in the `href` attribute, but that in this case that value is blank, resulting in an empty `href` value, which the browser interprets as a link to the current page.

**Comment by jpmckinney** [comment]
The buyer template doesn't check that there is a `uri` value to use. However, that template is no longer used, and only `organization.html` is used (which does check). So, this issue is closed.
