### ISSUE TITLE
Records: What should I see?

### ISSUE THREAD

**Issue by ekoner** [open-contracting/ocds-show#5]
I'm trying OCDS show on the [record sample data](https://github.com/open-contracting/sample-data/blob/ocds_upgrade_33/fictional-example/record/ocds-213czf-000-00001.json). I expected to see some information from each section but I only see Metadata. Could you clarify what should happen here?

**Comment by jpmckinney** [comment]
Hmm, sadly can't reproduce as data link is out-of-date, so closing. Can re-open with new link!
