### ISSUE TITLE
Notifications for invalid OCDS release structures?

### ISSUE THREAD

**Issue by patxiworks** [open-contracting/ocds-show#7]
What release formats are accepted on OCDS Show? 

[This release info](https://github.com/open-contracting/ocds-show/files/776521/ocds-azam7x-0dksxlng-ubec_release.json.zip) isn't displaying (using the text input) and yet no error is reported. Perhaps, the release isn't validly structured but can the user be notified somehow?

Thanks.

**Comment by duncandewhurst** [comment]
Hi Patrick, thanks for flagging this.

Right now OCDS Show accepts [release package](http://standard.open-contracting.org/latest/en/schema/release_package/) or [record package](http://standard.open-contracting.org/latest/en/schema/record_package/) files, so your release package should work, however as the tool is still in development, error messaging hasn't been added yet.

Running your data through the validator does result in [some errors]( http://standard.open-contracting.org/validator/data/7f8400d3-5603-4127-9785-a96672acc833 ), mostly blank fields, which may be causing the problem.

If you can get your release package to pass the validator it should work with the current version of OCDS Show.

I'll assign this over to the dev team to look at.

Thanks!

Duncan

**Comment by patxiworks** [comment]
Thanks a lot Duncan. I'll check the data and try to fix the errors.

**Comment by jpmckinney** [comment]
It's not anticipated at this time for OCDS Show to pass data to CoVE, so closing.
