### ISSUE TITLE
Visualisations

### ISSUE THREAD

**Issue by robredpath** [open-contracting/ocds-show#8]
"implementing some simple charts"

**Comment by robredpath** [comment]
Needs to have the shareholders pie chart as an example of how visualisations can work

**Comment by edugomez** [comment]
Not a PR but a push to ppp branch with a single commit https://github.com/open-contracting/ocds-show/commit/ee4a93a1d3a6e0786fc2d7f538ecc86c5bca2ef6

**Comment by edugomez** [comment]
![piechart](https://cloud.githubusercontent.com/assets/5618508/24924269/2032a988-1eec-11e7-91d9-e8355e835b0e.png)

**Comment by robredpath** [comment]
Nice :)

**Comment by robredpath** [comment]
Where can I see this on the Internet, @edugomez ?

**Comment by edugomez** [comment]
@robredpath https://open-contracting.github.io/ocds-show-ppp/, use this file https://github.com/open-contracting/ocds-show/blob/ppp/example/fake-ppp-release-package.json

**Comment by robredpath** [comment]
Thanks @edugomez , looks great!

**Comment by kindly** [comment]
This has been complete in ee4a93a
