### ISSUE TITLE
Make compliant with final version of schema

### ISSUE THREAD

**Issue by robredpath** [open-contracting/ocds-show#9]
Once the final schema is approved, we can make OCDS Show compliant with it! This is expected to be completed on the 5th of April.

**Comment by duncandewhurst** [comment]
The latest version of the ppp schema is available [here](http://standard.open-contracting.org/ppp-extension/en/release-schema.json)

**Comment by robredpath** [comment]
@duncandewhurst - this is ready for your review

**Comment by kindly** [comment]
This is done for ppp
